config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: "pages#about"
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 20}
  validates :description, presence: true, length: { minimum: 10, maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show

  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was created successfully"
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article was deleted successfully"
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any?  %>
  <h3>The following errors prevented the article from being saved</h3>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @article, local: true do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

<%= link_to 'Cancel', article_path(@article) %>

app/views/articles/index.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">All Articles</h1>

  <div class="container">
    <% @articles.each do |article| %>
      <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
          <div class="card text-center shadow">
            <div class="card-header font-italic">
              by Anand Upadhya
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= link_to article.title, article, class: "text-success" %></h5>
              <p class="card-text"><%= truncate(article.description, length: 100) %></p>
              <%= link_to 'View', article_path(article), class: "btn btn-outline-success" %>
              <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-info" %>
              <%= link_to 'Delete', article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            </div>
            <div class="card-footer text-muted">
              <small>Created <%= time_ago_in_words(article.created_at) %> ago | Editted <%= time_ago_in_words(article.updated_at) %> ago</small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <p><%= link_to 'Add Article', new_article_path %></p>
</div>

app/views/articles/new.html.erb
<h1>Add Article</h1>

<%= render 'form' %>

<%= link_to 'Cancel', articles_path %>

app/views/articles/show.html.erb
<h1>Article Show Page</h1>

<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>

<p>
  <%= link_to 'Edit', edit_article_path(@article) %> |
  <%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %> |
  <%= link_to 'All Articles', articles_path %>
</p>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; Your Website</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-light">
  <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", about_path, class: "nav-link" %>
      </li>
      <%# <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> %>
      <%# <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li> %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div id="page-content">
  <h1>ABOUT</h1>

  <%= link_to 'Home', root_path %>
</div>

app/views/pages/home.html.erb
<div id="page-content">
  <div class="container mt-4">
    <div class="jumbotron text-center text-white">
      <h1 class="display-4 font-weight-bold">Alpha Blog</h1>
      <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
      <hr class="my-4">
      <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <a class="btn btn-success btn-lg" href="#" role="button">Learn more</a>
    </div>
  </div>
  <%= link_to 'Articles', articles_path %>
  <%= link_to 'About', about_path %>
</div>